### ISSUE TITLE
Определить поведение сдвига в критических точках

### ISSUE THREAD

**Issue by suhanovgleb** [softwareDevelopmentProcessP3418/urban-octo-waffle#14]
Если мы в момент сдвига указателя влево находимся на нулевой ячейке, то указатель начнёт указывать на -1 ячейку, которой не существует. В таком случае нам следует определиться с возможным поведением в таком случае. Насколько я понимаю не существует единого мнения по поводу того, как такая ситуация должна обрабатываться.
Я вижу три варианта:
1) Кидать ошибку "выход за пределы памяти".
2) Не запрещать сдвиг, но тогда при использовании оператора + или - мы обратимся к последней ячейке памяти. Это некорректно, если у нас будет расширяющаяся память.
3) После ухода ptr в минус игнорировать последующие команды изменения памяти.

_Originally posted by @suhanovgleb in https://github.com/softwareDevelopmentProcessP3418/urban-octo-waffle/pull/13_

**Comment by mineralochka** [comment]
использовать предложенное в #15 решение
