### ISSUE TITLE
Поддержка символов .,

### ISSUE THREAD

**Issue by mineralochka** [softwareDevelopmentProcessP3418/urban-octo-waffle#23]
Команда Brainfuck | Эквивалент на Си | Описание команды
-- | -- | --
. | putchar(arr[i]); | напечатать значение из текущей ячейки
, | arr[i] = getchar(); | ввести извне значение и сохранить в текущей ячейке

**Comment by mineralochka** [comment]
извне == stdin

**Comment by Alefpeneash** [comment]
Откуда извне?
> ввести извне значение и сохранить в текущей ячейке
