### ISSUE TITLE
Поддержка символов []

### ISSUE THREAD

**Issue by mineralochka** [softwareDevelopmentProcessP3418/urban-octo-waffle#24]
Команда Brainfuck | Эквивалент на Си | Описание команды
-- | -- | --
[ | while(arr[i]){ | если значение текущей ячейки ноль, перейти вперёд по тексту программы на ячейку, следующую за соответствующей ] (с учётом вложенности)
] | } | если значение текущей ячейки не нуль, перейти назад по тексту программы на символ [ (с учётом вложенности)

**Comment by suhanovgleb** [comment]
Решено отложить на следующие релизы, если таковые будут
